on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - "script/*"
env:
  version: m131-f7f63e2

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: python3 script/checkout.py --version ${{ env.version }}
      - shell: bash
        run: dir
      - shell: bash
        run: python3 script/build.py --build-type ${{ matrix.build_type }}
      - shell: bash
        run: python3 script/archive.py --version ${{ env.version }} --build-type ${{ matrix.build_type }}
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.version }}-windows-${{ matrix.build_type }}-x64.zip
          path: '*.zip'
